Repository GinierClasses/holydraw, pull requests merged in 2021-04, with the labels that each got.

#233 T202 send socket on element finish
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/DTO/SessionDto.cs
  thyrel-api/thyrel-api/Models/DTO/SessionSocketDto.cs
  thyrel-web/.eslintrc
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/home/PlayerForm.tsx
  thyrel-web/src/components/room/draw/CanvasDraw.tsx
  thyrel-web/src/components/room/lobby/LobbyStartAction.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
  thyrel-web/src/components/room/start/StartForm.tsx
  thyrel-web/src/hooks/SessionProvider.tsx
  thyrel-web/src/hooks/useSessionStates.tsx
  thyrel-web/src/hooks/useWebsocket.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/types/HolyElement.type.ts
  thyrel-web/src/types/Session.type.ts
Labels: 🚀frontend

#235 T189 add time for all types of games
  thyrel-api/test_thyrel_api/StepTimerHandlerTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Handler/StepTimeHandler.cs
  thyrel-api/thyrel-api/Models/DTO/RoomDto.cs
  thyrel-api/thyrel-api/Models/Element.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Session.cs
Labels: ❄️backend

#243 Fix: previous element security and styles of Start Pages
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/Models/DTO/ElementDto.cs
  thyrel-api/thyrel-api/Models/DTO/ElementStepDto.cs
  thyrel-web/src/components/AppTitle.tsx
  thyrel-web/src/components/BigInput.tsx
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/HolyDrawLogo.tsx
  thyrel-web/src/components/room/DirectiveLabel.tsx
  thyrel-web/src/components/room/GameLayout.tsx
  thyrel-web/src/components/room/StepProgress.tsx
  thyrel-web/src/components/room/draw/SizePicker.tsx
  thyrel-web/src/components/room/start/StartForm.tsx
  thyrel-web/src/images/gym-guy.svg
  thyrel-web/src/images/holydraw-logo.svg
  thyrel-web/src/index.css
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/room/Lobby.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/theme.ts
Labels: 🚀frontend

#247 T219 BookDrawingElement
  thyrel-web/src/components/room/CurrentDrawImage.tsx
  thyrel-web/src/components/room/book/BookDrawingElement.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Write.tsx
Labels: 🚀frontend

#248 T222 default sentences
  thyrel-web/src/components/room/start/SentenceForm.tsx
  thyrel-web/src/hooks/useRandomSentence.tsx
  thyrel-web/src/hooks/useRandomUsername.tsx
Labels: 🚀frontend

#237 T218 create book sentence element component
  thyrel-web/src/components/room/book/BookSentenceElement.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#254 Drawing page
  thyrel-web/src/components/canvas/DrawingCanvas.tsx
  thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
  thyrel-web/src/components/canvas/canvas.type.ts
  thyrel-web/src/components/canvas/useCanvasEventListener.tsx
  thyrel-web/src/components/room/draw/CanvasActionButtons.tsx
  thyrel-web/src/components/room/draw/DrawColorPicker.tsx
  thyrel-web/src/components/room/draw/GameCanvas.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Draw.tsx
Labels: 🚀frontend

#258 Modal on kick instead of default alert window
  thyrel-web/src/components/room/lobby/KickModal.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
Labels: 🚀frontend

#263 T253 possibility for player to enter link in modal
  thyrel-web/src/components/home/ButtonModalJoin.tsx
  thyrel-web/src/components/home/PlayerForm.tsx
Labels: 🚀frontend

#275 CurrentAlbumId
  db-sqldump/thyrel-db.sql
  thyrel-api/test_thyrel_api/MockDatabase.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Models/DTO/SessionDto.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Room.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-web/src/types/Session.type.ts
Labels: 💾BDD

#274 Waiting book page
  reload-db.sh
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/room/GameLayout.tsx
  thyrel-web/src/components/room/book/BookStartAction.tsx
  thyrel-web/src/components/room/lobby/StartButton.tsx
  thyrel-web/src/pages/room/Book.tsx
Labels: 🚀frontend

#271 T195 redirect playing player to game page
  thyrel-web/src/hooks/RoomProvider.tsx
Labels: 🚀frontend

#280 T270 add next album controller
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Handler/AlbumStepTimeout.cs
  thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/DTO/ElementAlbumDto.cs
  thyrel-api/thyrel-api/Models/DTO/FinishElementDto.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
  thyrel-web/src/components/room/book/BookStartAction.tsx
  thyrel-web/src/hooks/AlbumProvider.tsx
  thyrel-web/src/pages/room/Book.tsx
  thyrel-web/src/types/websocket.types.ts
Labels: ❄️backend, 🚀frontend

#277 273: Add deploy settings for c# app
  .github/workflows/deploy.yml
  .gitignore
  thyrel-api/test_thyrel_api/ElementControllerTest.cs
  thyrel-api/test_thyrel_api/PlayerControllerTest.cs
  thyrel-api/test_thyrel_api/SessionControllerTest.cs
  thyrel-api/test_thyrel_api/TestProvider.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
  thyrel-api/thyrel-api/Json/JsonBase.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-api/thyrel-api/Properties/launchSettings.json
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
  thyrel-api/thyrel-api/Websocket/WebsocketMessageService.cs
  thyrel-api/thyrel-api/appsettings.json
  thyrel-api/thyrel-api/thyrel-api.csproj
  thyrel-web/.env
  thyrel-web/package-lock.json
  thyrel-web/package.json
  thyrel-web/src/__tests__/PlayerForm.test.tsx
  thyrel-web/src/api/client.tsx
  thyrel-web/src/components/room/book/BookMock.tsx
  thyrel-web/src/hooks/useWebsocket.tsx
  thyrel-web/src/pages/DevNav.tsx
  thyrel-web/src/pages/room/Book.tsx
  thyrel-web/src/test/handlers.ts
Labels: ❄️backend, 💾BDD

#281 T188 save draw before next step
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-web/src/components/canvas/DrawingCanvasActions.tsx
  thyrel-web/src/components/room/start/SentenceForm.tsx
Labels: ❄️backend, 🚀frontend

#304 T285 update btn and input components
  thyrel-web/public/index.html
  thyrel-web/src/__tests__/BigInput.test.tsx
  thyrel-web/src/components/AppLayout.tsx
  thyrel-web/src/components/BigButton.tsx
  thyrel-web/src/components/BigInput.tsx
  thyrel-web/src/components/canvas/DrawingCanvas.tsx
  thyrel-web/src/components/home/ButtonModalJoin.tsx
  thyrel-web/src/components/home/PlayerAvatar.tsx
  thyrel-web/src/components/room/CurrentDrawImage.tsx
  thyrel-web/src/components/room/DirectiveLabel.tsx
  thyrel-web/src/components/room/StepProgress.tsx
  thyrel-web/src/components/room/book/BookPlayerAvatar.tsx
  thyrel-web/src/components/room/book/BookPlayerList.tsx
  thyrel-web/src/components/room/book/BookSentenceElement.tsx
  thyrel-web/src/components/room/draw/SizePicker.tsx
  thyrel-web/src/components/room/lobby/KickModal.tsx
  thyrel-web/src/components/room/lobby/PlayerCard.tsx
  thyrel-web/src/pages/DevNav.tsx
  thyrel-web/src/test/mui-data.ts
  thyrel-web/src/theme.ts
Labels: 🚀frontend

#308 T287 update draw component
  thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
  thyrel-web/src/components/canvas/canvas.type.ts
  thyrel-web/src/components/canvas/useCanvasEventListener.tsx
  thyrel-web/src/components/room/draw/GameCanvas.tsx
  thyrel-web/src/components/room/draw/useDisableBodyOverflow.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Draw.tsx
  thyrel-web/src/theme.ts
Labels: 🚀frontend
