Repository GinierClasses/holydraw, pull requests merged in 2021-02, with the labels that each got.

#45 T8 link db to backend
  .DS_Store
  docker-compose.yml
  thyrel-api/thyrel-api/Controllers/ModelsControllers/TokenController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Models/Drawing.cs
  thyrel-api/thyrel-api/Models/DrawingContext.cs
  thyrel-api/thyrel-api/Models/GameSessionContext.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Sentence.cs
  thyrel-api/thyrel-api/Models/SentenceContext.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-api/thyrel-api/Models/Token.cs
  thyrel-api/thyrel-api/Models/TokenContext.cs
  thyrel-api/thyrel-api/Models/UserContext.cs
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/thyrel-api.csproj
Labels: ❄️backend, 💾BDD

#47 Updated DB and Models
  db-sqldump/thyrel-db.sql
  package.json
  thyrel-api/thyrel-api/Models/Drawing.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Room.cs
  thyrel-api/thyrel-api/Models/Sentence.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-web/package-lock.json
Labels: ❄️backend, 💾BDD

#48 T19 create utils to fetch api
  thyrel-web/.env-template
  thyrel-web/.gitignore
  thyrel-web/package.json
  thyrel-web/src/__tests__/App.test.tsx
  thyrel-web/src/__tests__/client.test.tsx
  thyrel-web/src/api/client.tsx
  thyrel-web/src/api/player-provider.tsx
  thyrel-web/src/setupTests.ts
  thyrel-web/src/test/data.ts
  thyrel-web/src/test/data/client.json
  thyrel-web/src/test/handlers.ts
  thyrel-web/src/test/server.ts
  thyrel-web/yarn.lock
Labels: 🚀frontend

#49 API - DB linking
  db-sqldump/thyrel-db.sql
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Room.cs
  thyrel-api/thyrel-api/Models/Sentence.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-web/.env
Labels: ❄️backend, 💾BDD

#52 [add] UserCard Component
  thyrel-web/.eslintrc
  thyrel-web/src/__tests__/UserCard.test.tsx
  thyrel-web/src/components/lobby/UserCard.tsx
  thyrel-web/src/index.css
  thyrel-web/src/pages/Lobby.tsx
  thyrel-web/src/styles/colors.ts
Labels: 🚀frontend

#54 Create room controller
  thyrel-api/thyrel-api/Controllers/ModelsControllers/RoomController.cs
Labels: ❄️backend

#53 Creating Player controller
  thyrel-api/thyrel-api/Controllers/ModelsControllers/PlayerController.cs
  thyrel-api/thyrel-api/Models/Player.cs
Labels: ❄️backend

#56 fix relation bug and add new dumb
  db-sqldump/thyrel-db.sql
  thyrel-api/thyrel-api/Controllers/ModelsControllers/PlayerController.cs
  thyrel-api/thyrel-api/Controllers/ModelsControllers/RoomController.cs
  thyrel-api/thyrel-api/Controllers/ModelsControllers/TokenController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Room.cs
  thyrel-api/thyrel-api/Models/Sentence.cs
  thyrel-api/thyrel-api/Models/Token.cs
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/thyrel-api.csproj
Labels: ❄️backend

#66 Title component react
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-web/src/components/lobby/AppTitle.tsx
  thyrel-web/src/index.css
  thyrel-web/src/pages/Lobby.tsx
  thyrel-web/yarn.lock
Labels: 🚀frontend

#67 T34 create big button
  .github/pull_request_template.md
  thyrel-web/src/__tests__/BigButton.test.tsx
  thyrel-web/src/components/BigButton.tsx
Labels: 🚀frontend

#65 T50 add websocket in backend
  thyrel-api/thyrel-api/Controllers/ModelsControllers/TokenController.cs
  thyrel-api/thyrel-api/Controllers/StreamController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/Websocket/IWebsocketHandler.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
  thyrel-web/src/Routes.tsx
  thyrel-web/src/pages/TestWebsocket.tsx
Labels: ❄️backend

#73 T68 add room context provider
  db-sqldump/thyrel-db.sql
  thyrel-api/thyrel-api/Controllers/MPlayerController.cs
  thyrel-api/thyrel-api/Controllers/MRoomController.cs
  thyrel-api/thyrel-api/Controllers/MTokenController.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Token.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
  thyrel-api/thyrel-api/Websocket/WebsocketJson.cs
  thyrel-web/src/Routes.tsx
  thyrel-web/src/api/client.tsx
  thyrel-web/src/api/player-provider.tsx
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/hooks/useWebsocket.tsx
  thyrel-web/src/pages/DevNav.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/Lobby.tsx
  thyrel-web/src/pages/TestAPI.tsx
  thyrel-web/src/pages/TestWebsocket.tsx
  thyrel-web/src/pages/room/Book.tsx
  thyrel-web/src/pages/room/Draw.tsx
  thyrel-web/src/pages/room/Lobby.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/pages/room/Write.tsx
  thyrel-web/src/types/Player.type.ts
  thyrel-web/src/types/Room.type.ts
  thyrel-web/src/types/Token.type.ts
  thyrel-web/src/utils/json.ts
Labels: ❄️backend

#82 Update Models and DB
  db-sqldump/thyrel-db.sql
  thyrel-api/thyrel-api/Models/Drawing.cs
  thyrel-api/thyrel-api/Models/Element.cs
  thyrel-api/thyrel-api/Models/ElementType.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Session.cs
Labels: ❄️backend, 💾BDD, 🔥high-priority

#85 Create timer component
  thyrel-web/src/Routes.tsx
  thyrel-web/src/__tests__/StepTimer.test.tsx
  thyrel-web/src/components/StepTimer.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/DevNav.tsx
  thyrel-web/src/styles/Box.tsx
Labels: 🚀frontend

#84 T62 create the big input
  thyrel-web/package.json
  thyrel-web/src/Routes.tsx
  thyrel-web/src/__tests__/BigInput.test.tsx
  thyrel-web/src/components/lobby/BigInput.tsx
  thyrel-web/src/hooks/useMediaQuery.ts
  thyrel-web/src/index.css
  thyrel-web/src/pages/DevNav.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/Lobby.tsx
  thyrel-web/src/styles/breakpoint.ts
  thyrel-web/src/styles/colors.ts
Labels: 🚀frontend

#92 add the SessionDataProvider
  thyrel-api/thyrel-api/Controllers/ModelsControllers/SessionDataProvider.cs
Labels: ❄️backend

#90 T59 add join controller
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-web/src/pages/Home.tsx
Labels: 🚀frontend

#93 T71 add element data provider
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/Models/Element.cs
Labels: ❄️backend

#86 Creation of AvatarCard component
  thyrel-web/src/__tests__/AvatarCard.test.tsx
  thyrel-web/src/components/BigButton.tsx
  thyrel-web/src/components/Home/AvatarCard.tsx
  thyrel-web/src/components/lobby/UserCard.tsx
  thyrel-web/src/images/profiles/pp-1.png
  thyrel-web/src/images/profiles/pp-2.png
  thyrel-web/src/images/profiles/pp-3.png
  thyrel-web/src/images/profiles/pp-4.png
  thyrel-web/src/images/profiles/pp-5.png
  thyrel-web/src/images/profiles/pp-6.png
  thyrel-web/src/images/profiles/pp-7.png
  thyrel-web/src/images/profiles/pp-8.png
  thyrel-web/src/images/profiles/profiles-pictures.ts
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/styles/Box.tsx
  thyrel-web/src/styles/colors.ts
Labels: 🚀frontend

#98 T72 add getRoom Controller
  thyrel-api/thyrel-api/Controllers/RoomController.cs
Labels: ❄️backend

#96 T81 update data provider with async
  thyrel-api/thyrel-api/Controllers/ModelsControllers/SessionDataProvider.cs
  thyrel-api/thyrel-api/Controllers/PlayerDataProvider.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/Controllers/TokenDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ITokenDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/TokenDataProvider.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Room.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
Labels: ❄️backend

#97 StartSession Controller
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
Labels: ❄️backend

#101 UserCardList component
  thyrel-web/src/__tests__/UserCardList.test.tsx
  thyrel-web/src/components/lobby/UserCardList.tsx
  thyrel-web/src/index.css
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/TestAPI.tsx
  thyrel-web/src/styles/Box.tsx
  thyrel-web/src/types/Player.type.ts
Labels: 🚀frontend

#110 T16 add UI of HomePage
  thyrel-web/src/components/AppLayout.tsx
  thyrel-web/src/components/lobby/AppTitle.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/Home.tsx
Labels: 🚀frontend

#109 RoomDataProvider .NET test
  thyrel-api/test_thyrel_api/RoomDataProviderTest.cs
  thyrel-api/test_thyrel_api/TokenElementProviderTestcs.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/Websocket/WebsocketJson.cs
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: ❄️backend

#108 PlayerCount component
  thyrel-web/src/__tests__/PlayerCount.test.tsx
  thyrel-web/src/__tests__/UserCardList.test.tsx
  thyrel-web/src/components/PlayerCount.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#113 Index Identifier and TokenKey
  db-sqldump/thyrel-db.sql
Labels: 💾BDD

#100 T74 add Authorization Handler
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Handler/AuthorizationHandler.cs
Labels: ❄️backend

#115 PATCH/ElementController
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
Labels: ❄️backend

#121 DirectiveLabel Component
  thyrel-web/src/__tests__/PlayerAvatar.test.tsx
  thyrel-web/src/__tests__/PlayerCount.test.tsx
  thyrel-web/src/__tests__/StepTimer.test.tsx
  thyrel-web/src/components/home/PlayerAvatar.tsx
  thyrel-web/src/components/room/DirectiveLabel.tsx
  thyrel-web/src/components/room/PlayerCount.tsx
  thyrel-web/src/components/room/StepTimer.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/styles/Box.tsx
Labels: 🚀frontend

#118 T116 add player providers
  thyrel-api/thyrel-api/Controllers/PlayerController.cs
  thyrel-web/src/Routes.tsx
  thyrel-web/src/hooks/PlayerProvider.tsx
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/pages/room/Lobby.tsx
Labels: ❄️backend, 🚀frontend

#133 SizePicker Component
  thyrel-web/src/components/room/SizePicker.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/styles/Box.tsx
  thyrel-web/yarn.lock
Labels: 🚀frontend

#136 T102 add test session data provider
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
Labels: ❄️backend
