Repository GinierClasses/holydraw, pull requests merged in 2021-01, with the labels that each got.

#14 add base API + test controller
  .DS_Store
  .gitignore
  thyrel-api/.gitignore
  thyrel-api/thyrel-api.sln
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Program.cs
  thyrel-api/thyrel-api/Properties/launchSettings.json
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/appsettings.Development.json
  thyrel-api/thyrel-api/appsettings.json
  thyrel-api/thyrel-api/thyrel-api.csproj
Labels: ❄️backend

#13 create react app
  thyrel-web/.eslintcache
  thyrel-web/.eslintrc
  thyrel-web/.gitignore
  thyrel-web/README.md
  thyrel-web/package-lock.json
  thyrel-web/package.json
  thyrel-web/public/favicon.ico
  thyrel-web/public/index.html
  thyrel-web/public/logo192.png
  thyrel-web/public/logo512.png
  thyrel-web/public/manifest.json
  thyrel-web/public/robots.txt
  thyrel-web/src/App.test.tsx
  thyrel-web/src/App.tsx
  thyrel-web/src/Routes.tsx
  thyrel-web/src/index.css
  thyrel-web/src/index.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/Lobby.tsx
  thyrel-web/src/pages/TestAPI.tsx
  thyrel-web/src/react-app-env.d.ts
  thyrel-web/src/setupTests.ts
  thyrel-web/tsconfig.json
Labels: 🚀frontend

#25 Created SQL database
  .gitignore
  db-sqldump/thyrel-db.sql
  docker-compose.yml
Labels: 💾BDD

#26 Issue 22: Add UI Library for Front-App
  thyrel-web/.prettierignore
  thyrel-web/.prettierrc
  thyrel-web/README.md
  thyrel-web/config-overrides.js
  thyrel-web/package.json
  thyrel-web/src/App.tsx
  thyrel-web/src/index.css
  thyrel-web/src/index.less
  thyrel-web/src/index.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/TestAPI.tsx
  thyrel-web/src/rsuite-custom-theme.less
  thyrel-web/tsconfig.json
Labels: 🚀frontend

#28 Loads SQL dump on image creation
  db-sqldump/thyrel-db.sql
  docker-compose.yml
Labels: 💾BDD

#30 Docker images reload script
  reload-db.sh
Labels: 💾BDD

#31 T6 create cs models
  thyrel-api/thyrel-api/Models/Drawing.cs
  thyrel-api/thyrel-api/Models/DrawingContext.cs
  thyrel-api/thyrel-api/Models/GameSession.cs
  thyrel-api/thyrel-api/Models/GameSessionContext.cs
  thyrel-api/thyrel-api/Models/Sentence.cs
  thyrel-api/thyrel-api/Models/SentenceContext.cs
  thyrel-api/thyrel-api/Models/Token.cs
  thyrel-api/thyrel-api/Models/TokenContext.cs
  thyrel-api/thyrel-api/Models/User.cs
  thyrel-api/thyrel-api/Models/UserContext.cs
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/thyrel-api.csproj
Labels: ❄️backend
