Repository GinierClasses/holydraw, pull requests merged in 2021-03, with the labels that each got.

#138 Start React View
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/images/gym-guy.svg
  thyrel-web/src/pages/room/Start.tsx
Labels: 🚀frontend

#147 BookPlayerList component
  thyrel-web/src/components/room/BookPlayerList.tsx
  thyrel-web/src/index.css
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/styles/Box.tsx
Labels: 🚀frontend

#149 feat: Start react view is now responsive
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/room/StepTimer.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/setupTests.ts
Labels: 🚀frontend

#157 T76 ShareRoomButton component
  thyrel-web/src/components/lobby/ShareRoomButton.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/utils/clipboard.tsx
Labels: 🚀frontend

#150 T17 create UI of lobby
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/test_thyrel_api/PlayerDataProviderTest.cs
  thyrel-api/test_thyrel_api/RoomDataProviderTest.cs
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/test_thyrel_api/TokenElementProviderTestcs.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/Controllers/PlayerController.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/TokenDataProvider.cs
  thyrel-api/thyrel-api/Handler/AuthorizationHandler.cs
  thyrel-api/thyrel-api/Json/BaseWebsocketEventJson.cs
  thyrel-api/thyrel-api/Json/ConnexionSocketMessage.cs
  thyrel-api/thyrel-api/Json/JSON.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/SocketConnection.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
  thyrel-api/thyrel-api/Websocket/WebsocketJson.cs
  thyrel-api/thyrel-api/appsettings.Development.json
  thyrel-api/thyrel-api/thyrel-api.csproj
  thyrel-web/package.json
  thyrel-web/src/Routes.tsx
  thyrel-web/src/components/BigButton.tsx
  thyrel-web/src/components/Loading.tsx
  thyrel-web/src/components/SpinnerIcon.tsx
  thyrel-web/src/components/home/PlayerForm.tsx
  thyrel-web/src/components/lobby/LobbyStartButton.tsx
  thyrel-web/src/components/lobby/PlayerCard.tsx
  thyrel-web/src/components/lobby/PlayerCardList.tsx
  thyrel-web/src/components/lobby/Players.tsx
  thyrel-web/src/components/lobby/SettingsMenu.tsx
  thyrel-web/src/hooks/PlayerProvider.tsx
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/hooks/WebsocketProvider.tsx
  thyrel-web/src/hooks/useRoomStates.tsx
  thyrel-web/src/hooks/useWebsocket.tsx
  thyrel-web/src/images/spinner.svg
  thyrel-web/src/index.css
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/Home.tsx
  thyrel-web/src/pages/Lobby.tsx
  thyrel-web/src/pages/room/Lobby.tsx
  thyrel-web/src/types/Room.type.ts
  thyrel-web/yarn.lock
Labels: 🚀frontend

#163 T130 add modal join
  thyrel-web/src/__tests__/PlayerForm.test.tsx
  thyrel-web/src/components/home/ButtonModalJoin.tsx
  thyrel-web/src/components/home/PlayerForm.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#162 Start Session Behaviors
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/lobby/LobbyStartButton.tsx
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/types/Session.type.ts
Labels: ❄️backend, 🚀frontend

#161 T142 create kick controller
  db-sqldump/thyrel-db.sql
  thyrel-api/test_thyrel_api/PlayerDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/PlayerController.cs
  thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
Labels: ❄️backend

#165 add: controller tests
  thyrel-api/test_thyrel_api/PlayerControllerTest.cs
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
  thyrel-api/test_thyrel_api/TestProvider.cs
  thyrel-api/thyrel-api/Controllers/PlayerController.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
  thyrel-web/src/api/client.tsx
  thyrel-web/src/hooks/useRoomStates.tsx
Labels: ❄️backend

#171 add: DrawColorPicker now change colors when you click on them
  thyrel-web/src/components/room/draw/DrawColorPicker.tsx
  thyrel-web/src/components/room/draw/SizePicker.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 💣 bug, 🚀frontend, 🧹code cleaning

#173 Fix firefox bug
  thyrel-web/src/components/room/draw/SizePicker.tsx
Labels: 💣 bug, 🚀frontend, 🧹code cleaning

#172 T167 refactor get controller
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
Labels: ❄️backend

#176 T158 handle on kick on frontend
  thyrel-api/test_thyrel_api/PlayerDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/PlayerController.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-web/src/__tests__/PlayerCard.test.tsx
  thyrel-web/src/__tests__/PlayerCardList.test.tsx
  thyrel-web/src/components/room/lobby/PlayerCard.tsx
  thyrel-web/src/components/room/lobby/PlayerCardList.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/hooks/useRoomStates.tsx
Labels: ❄️backend, 📘SP-8, 🚀frontend

#177 T168 create kick controller test
  thyrel-api/test_thyrel_api/PlayerControllerTest.cs
Labels: ❄️backend, 📘SP-3

#199 add: adding a test for RoomController Post method
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
Labels: ❄️backend, 📘SP-3

#191 T160 add session provider
  db-sqldump/thyrel-db.sql
  package-lock.json
  package.json
  thyrel-api/test_thyrel_api/ElementControllerTest.cs
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/test_thyrel_api/ElementModelTest.cs
  thyrel-api/test_thyrel_api/MockDatabase.cs
  thyrel-api/test_thyrel_api/PlayerControllerTest.cs
  thyrel-api/test_thyrel_api/PlayerDataProviderTest.cs
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
  thyrel-api/test_thyrel_api/SessionControllerTest.cs
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/Controllers/PlayerController.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IPlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Handler/AuthorizationHandler.cs
  thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
  thyrel-api/thyrel-api/Json/JsonBase.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/DTO/ElementCandidateDto.cs
  thyrel-api/thyrel-api/Models/DTO/ElementDto.cs
  thyrel-api/thyrel-api/Models/DTO/PlayerDto.cs
  thyrel-api/thyrel-api/Models/DTO/SessionSocketDto.cs
  thyrel-api/thyrel-api/Models/Element.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Session.cs
  thyrel-api/thyrel-api/Models/SessionStepType.cs
  thyrel-api/thyrel-api/Models/Token.cs
  thyrel-api/thyrel-api/Startup.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
  thyrel-web/src/Routes.tsx
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/room/lobby/LobbyStartAction.tsx
  thyrel-web/src/hooks/PlayerProvider.tsx
  thyrel-web/src/hooks/RoomProvider.tsx
  thyrel-web/src/hooks/SessionProvider.tsx
  thyrel-web/src/hooks/WebsocketProvider.tsx
  thyrel-web/src/hooks/useRoomStates.tsx
  thyrel-web/src/hooks/useSessionStates.tsx
  thyrel-web/src/hooks/useWebsocket.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/types/HolyElement.type.ts
  thyrel-web/src/types/Session.type.ts
Labels: ❄️backend, 🚀frontend

#205 T190 fix bug copy url
  thyrel-web/src/components/room/lobby/SettingsMenu.tsx
  thyrel-web/src/components/room/lobby/ShareRoomButton.tsx
Labels: 💣 bug, 🚀frontend

#201 Responsive lobby
  thyrel-web/src/__tests__/BookPlayerList.test.tsx
  thyrel-web/src/__tests__/json/players.json
  thyrel-web/src/components/room/book/BookPlayerList.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Lobby.tsx
  thyrel-web/src/test/media-query-mock.ts
Labels: 🚀frontend

#210 Display current player on lobby
  thyrel-web/src/__tests__/PlayerCard.test.tsx
  thyrel-web/src/components/room/lobby/PlayerCard.tsx
  thyrel-web/src/components/room/lobby/PlayerCardList.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#204 T194 loading state for home buttons
  thyrel-web/src/components/home/ButtonModalJoin.tsx
  thyrel-web/src/components/home/PlayerForm.tsx
Labels: 🚀frontend

#211 T208 add drawimage column on element
  db-sqldump/thyrel-db.sql
Labels: 💾BDD

#213 New spinner on loading component
  thyrel-web/src/images/spinner.svg
Labels: 🚀frontend

#214 T128 add default username
  thyrel-web/src/components/home/PlayerForm.tsx
  thyrel-web/src/hooks/useRandomUsername.tsx
Labels: 🚀frontend

#206 T143 element controller get previous element
  thyrel-api/test_thyrel_api/ElementControllerTest.cs
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-api/thyrel-api/Models/DTO/ElementStepDto.cs
Labels: ❄️backend

#217 OnFinish upgrade and drawimage in backend
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/test_thyrel_api/ElementModelTest.cs
  thyrel-api/test_thyrel_api/MockDatabase.cs
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Models/DTO/PlayerStatusDto.cs
  thyrel-api/thyrel-api/Models/Element.cs
Labels: ❄️backend

#221 If timer is under 5 second and everyone is done with their element, don't switch.
  thyrel-api/thyrel-api/Controllers/ElementController.cs
Labels: ❄️backend

#209 T182 add draw component
  thyrel-web/src/components/room/draw/CanvasDraw.tsx
  thyrel-web/src/components/room/draw/CanvasDrawActions.tsx
  thyrel-web/src/components/room/draw/useCanvasEventListener.tsx
  thyrel-web/src/components/room/draw/useCanvasPaint.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/types/canvas.types.ts
  thyrel-web/src/utils/canvas.utils.ts
  thyrel-web/src/utils/clipboard.ts
  thyrel-web/tsconfig.json
Labels: 🚀frontend

#226 T192 return session dto with current and total steps
  db-sqldump/thyrel-db.sql
  thyrel-api/test_thyrel_api/MockDatabase.cs
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/DataProvider/ISessionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/SessionDataProvider.cs
  thyrel-api/thyrel-api/Models/DTO/SessionDto.cs
  thyrel-api/thyrel-api/Models/Session.cs
Labels: ❄️backend, 💾BDD, 📘SP-5

#227 StartSession() Tests
  thyrel-api/test_thyrel_api/SessionDataProviderTest.cs
Labels: ❄️backend

#228 T174 finish room when empty
  thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/PlayerDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/Handler/SessionStepTimeout.cs
  thyrel-api/thyrel-api/Websocket/WebsocketHandler.cs
Labels: ❄️backend

#230 StepLabel Component
  thyrel-web/src/components/room/StepProgress.tsx
  thyrel-web/src/components/room/book/BookPlayerList.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#232 T159 handle on finish on start page
  thyrel-api/test_thyrel_api/ElementDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/ElementDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/IElementDataProvider.cs
  thyrel-api/thyrel-api/Models/DTO/ElementDto.cs
  thyrel-web/src/hooks/SessionProvider.tsx
  thyrel-web/src/pages/room/Start.tsx
Labels: 🚀frontend
