Repository GinierClasses/holydraw, pull requests merged in 2021-05, with the labels that each got.

#309 add: possibilities to only add a point on canvas
  thyrel-web/src/components/canvas/useCanvasPaint.tsx
  thyrel-web/src/types/canvas.types.ts
  thyrel-web/src/utils/canvas.utils.ts
Labels: 🚀frontend

#310 T295 update BookSentenceElement
  thyrel-web/src/components/room/book/BookMock.tsx
  thyrel-web/src/components/room/book/BookSentenceElement.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#318 T312 update button join w/ identifier
  thyrel-web/src/components/home/ButtonModalJoin.tsx
Labels: 💣 bug, 🚀frontend

#314 T292: update app and game layout
  thyrel-web/src/Routes.tsx
  thyrel-web/src/components/GameBar.tsx
  thyrel-web/src/components/room/GameLayout.tsx
  thyrel-web/src/components/room/StepProgress.tsx
  thyrel-web/src/components/room/StepTimer.tsx
  thyrel-web/src/pages/room/Book.tsx
Labels: 🚀frontend

#316 T315: Create the bucket tool
  thyrel-web/src/components/canvas/DrawingCanvasContext.tsx
  thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
  thyrel-web/src/components/canvas/useCanvasPaint.tsx
  thyrel-web/src/components/room/draw/CanvasLineTypeButtons.tsx
  thyrel-web/src/components/room/draw/DrawColorPicker.tsx
  thyrel-web/src/components/room/draw/GameCanvas.tsx
  thyrel-web/src/types/canvas.types.ts
  thyrel-web/src/utils/canvas.utils.ts
Labels: 🚀frontend

#313 T297: add: websocket on album start with new currentlabumid
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/DTO/SessionSocketDto.cs
Labels: ❄️backend

#328 PlayerCardV2
  thyrel-web/src/components/room/lobby/PlayerCard.tsx
Labels: 🚀frontend

#323 T284 create restart session controller
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/Controllers/SessionController.cs
  thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
Labels: ❄️backend

#319 T286 update start and write
  thyrel-api/thyrel-api/Startup.cs
  thyrel-web/src/components/room/CurrentDrawImage.tsx
  thyrel-web/src/components/room/DirectiveLabel.tsx
  thyrel-web/src/components/room/book/BookDrawingElement.tsx
  thyrel-web/src/components/room/start/SentenceForm.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/pages/room/Write.tsx
Labels: 🚀frontend

#325 SizePicker V2
  thyrel-web/src/components/room/draw/SizePickerV2.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#320 T261 create the book pages
  thyrel-web/src/components/BigButton.tsx
  thyrel-web/src/components/room/book/Album.tsx
  thyrel-web/src/components/room/book/BookMock.tsx
  thyrel-web/src/pages/room/Book.tsx
Labels: 🚀frontend

#332 T289 update color picker from new figma model
  thyrel-web/src/components/room/draw/DrawColorPicker.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Draw.tsx
  thyrel-web/src/utils/app-constant.ts
Labels: 🚀frontend

#333 add: vertical mobile hooks
  thyrel-web/src/hooks/useMobileHorizontalHook.ts
Labels: 🚀frontend

#327 T317 add circle button
  thyrel-web/src/Routes.tsx
  thyrel-web/src/components/canvas/useCanvasPaint.tsx
  thyrel-web/src/components/circle-button/CircleButton.tsx
  thyrel-web/src/components/circle-button/CircleButtons.tsx
  thyrel-web/src/components/room/GameLayout.tsx
  thyrel-web/src/components/room/draw/CanvasActionButtons.tsx
  thyrel-web/src/components/room/draw/GameCanvas.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#334 T294 create random color on color picker
  thyrel-web/src/components/room/draw/DrawColorPicker.tsx
  thyrel-web/src/components/room/draw/RandomColor.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Draw.tsx
  thyrel-web/src/utils/app-constant.ts
  thyrel-web/src/utils/utils.ts
Labels: 🚀frontend

#337 Color picker react
  thyrel-web/package-lock.json
  thyrel-web/package.json
  thyrel-web/src/components/room/draw/DrawColorPicker.tsx
  thyrel-web/src/components/room/draw/PreciseColorPicker.tsx
  thyrel-web/src/components/room/draw/RandomColor.tsx
Labels: 🚀frontend

#339 Update lobby
  thyrel-web/src/components/room/lobby/PlayerCard.tsx
  thyrel-web/src/components/room/lobby/SettingsMenu.tsx
  thyrel-web/src/components/room/lobby/ShareRoomButton.tsx
  thyrel-web/src/components/room/lobby/StartButton.tsx
  thyrel-web/src/pages/room/Lobby.tsx
Labels: 🚀frontend

#338 T307 mobile modal color picker
  thyrel-web/src/components/room/draw/ColorPickerMobileModal.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/utils/app-constant.ts
Labels: 🚀frontend

#356 New SQL table (Reaction) and new cell in room table (Mode)
  db-sqldump/thyrel-db.sql
Labels: 💾BDD

#358 T342: add refresh button
  thyrel-web/src/components/room/lobby/SettingsMenu.tsx
  thyrel-web/src/components/room/lobby/ShareRoomButton.tsx
Labels: 🚀frontend

#357 T322 add draw component desktop
  thyrel-web/src/components/AppLayout.tsx
  thyrel-web/src/components/canvas/DrawingCanvas.tsx
  thyrel-web/src/components/canvas/DrawingCanvasProvider.tsx
  thyrel-web/src/components/canvas/useCanvasEventListener.tsx
  thyrel-web/src/components/circle-button/CircleButtons.tsx
  thyrel-web/src/components/home/PlayerForm.tsx
  thyrel-web/src/components/room/draw/CanvasActionButtons.tsx
  thyrel-web/src/components/room/draw/DrawMobileHorizontal.tsx
  thyrel-web/src/components/room/draw/DrawMobileVertical.tsx
  thyrel-web/src/components/room/draw/GameCanvas.tsx
  thyrel-web/src/components/room/draw/PreciseColorPicker.tsx
  thyrel-web/src/components/room/draw/RandomColor.tsx
  thyrel-web/src/components/room/draw/desktop/CanvasActionButtons.tsx
  thyrel-web/src/components/room/draw/desktop/DesktopColorPicker.tsx
  thyrel-web/src/components/room/draw/desktop/DrawDesktop.tsx
  thyrel-web/src/components/room/draw/desktop/DrawDesktopCanvas.tsx
  thyrel-web/src/components/room/draw/desktop/SizePicker.tsx
  thyrel-web/src/components/room/draw/desktop/SizePickerV2.tsx
  thyrel-web/src/components/room/draw/useDisableBodyOverflow.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/pages/room/Draw.tsx
  thyrel-web/src/utils/canvas.utils.ts
Labels: 🚀frontend

#360 New reaction on Backend
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/Controllers/TestController.cs
  thyrel-api/thyrel-api/Models/Element.cs
  thyrel-api/thyrel-api/Models/EmojiReaction.cs
  thyrel-api/thyrel-api/Models/HolyDrawDbContext.cs
  thyrel-api/thyrel-api/Models/Player.cs
  thyrel-api/thyrel-api/Models/Reaction.cs
  thyrel-api/thyrel-api/Models/Room.cs
  thyrel-api/thyrel-api/Models/RoomMode.cs
Labels: ❄️backend

#371 T350 add controller for roommode
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
  thyrel-api/test_thyrel_api/RoomDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/DTO/RoomDto.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
Labels: ❄️backend

#363 T352 adapt sentences for mode
  thyrel-api/test_thyrel_api/MockDatabase.cs
  thyrel-api/test_thyrel_api/RoomControllerTest.cs
  thyrel-api/test_thyrel_api/RoomDataProviderTest.cs
  thyrel-api/thyrel-api/Controllers/RoomController.cs
  thyrel-api/thyrel-api/DataProvider/IRoomDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/RoomDataProvider.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/DTO/RoomDto.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
  thyrel-web/src/api/client.tsx
  thyrel-web/src/components/room/start/SentenceForm.tsx
  thyrel-web/src/hooks/useRandomSentence.tsx
  thyrel-web/src/pages/room/Start.tsx
  thyrel-web/src/types/Room.type.ts
  thyrel-web/src/types/websocket.types.ts
Labels: 🚀frontend

#369 T346 reaction element controller reaction data provider
  thyrel-api/thyrel-api/Controllers/ElementController.cs
  thyrel-api/thyrel-api/DataProvider/IReactionDataProvider.cs
  thyrel-api/thyrel-api/DataProvider/ReactionDataProvider.cs
  thyrel-api/thyrel-api/Json/WebsocketEventJson.cs
  thyrel-api/thyrel-api/Models/WebsocketEvent.cs
Labels: ❄️backend

#380 T351 restrictions one word + T362
  thyrel-web/src/components/room/book/BookDrawingElement.tsx
  thyrel-web/src/components/room/start/SentenceForm.tsx
Labels: 🚀frontend

#381 T365 366 room mode implementation
  thyrel-web/src/components/room/lobby/ModeCard.tsx
  thyrel-web/src/components/room/lobby/ModeModal.tsx
  thyrel-web/src/components/room/lobby/RoomModeSelector.tsx
  thyrel-web/src/components/room/lobby/SettingsMenu.tsx
  thyrel-web/src/pages/ComponentTest.tsx
Labels: 🚀frontend

#384 T361 save with enter
  thyrel-web/src/components/room/start/SentenceForm.tsx
Labels: 🚀frontend

#382 ReactionPicker
  thyrel-web/package-lock.json
  thyrel-web/src/components/room/book/BookAddReaction.tsx
  thyrel-web/src/components/room/book/BookPopper.tsx
  thyrel-web/src/components/room/book/ReactionEmoji.tsx
  thyrel-web/src/components/room/book/ReactionPicker.tsx
  thyrel-web/src/components/room/lobby/Players.tsx
  thyrel-web/src/pages/ComponentTest.tsx
  thyrel-web/src/types/Reaction.type.ts
Labels: 🚀frontend
